package com.unbeat.playlist.userplaylist

import com.unbeat.playlist.favoritetrack.FavoriteTrack
import com.unbeat.playlist.favoritetrack.FavoriteTrackRepository
import com.unbeat.playlist.userplaylist.dto.PlaylistResponse
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.format.DateTimeFormatter

/**
 * "새 재생목록 누르고 이름 타이핑해서 곡 하나하나 넣는 건 뻔하다, 내가 들은 곡을 분석해서
 * 장르별로 알아서 재생목록이 만들어졌으면 좋겠다"는 피드백으로 추가한 기능.
 *
 * PlaylistService(수동 CRUD)와 분리한 이유: 이 클래스만 FavoriteTrackRepository를 갖다 써서
 * "즐겨찾기 도메인을 읽어서 재생목록 도메인에 쓰는" 교차 로직을 한곳에 모아두기 위함 — 수동 CRUD는
 * 즐겨찾기를 몰라도 되는데, 여길 합쳐두면 그 경계가 흐려짐.
 */
@Service
class AutoPlaylistService(
    private val favoriteTrackRepository: FavoriteTrackRepository,
    private val playlistRepository: PlaylistRepository,
    private val playlistTrackRepository: PlaylistTrackRepository
) {

    /**
     * 즐겨찾기한 곡의 대표 태그(Last.fm 태그 중 가장 비중 높은 첫 번째)를 장르로 보고 묶음.
     * 버튼을 다시 눌러도 중복이 쌓이지 않도록, 이전에 자동 생성했던 재생목록은 지우고
     * 최신 즐겨찾기 기준으로 다시 만듦 — 수동으로 만든 재생목록(isAutoGenerated=false)은 건드리지 않음.
     */
    @Transactional
    fun generate(sessionId: String): List<PlaylistResponse> {
        val favorites = favoriteTrackRepository.findBySessionIdOrderByCreatedAtDesc(sessionId)

        val tracksByGenre: Map<String, List<FavoriteTrack>> = favorites
            .mapNotNull { track -> primaryGenreOf(track)?.let { genre -> genre to track } }
            .groupBy({ it.first }, { it.second })
            .filterValues { it.size >= MIN_TRACKS_PER_GENRE_PLAYLIST }

        val previousAuto = playlistRepository.findBySessionIdAndIsAutoGenerated(sessionId, true)
        previousAuto.forEach { playlistTrackRepository.deleteByPlaylistId(it.id!!) }
        playlistRepository.deleteAll(previousAuto)

        return tracksByGenre.map { (genreKey, tracksInGenre) ->
            val playlist = playlistRepository.save(
                Playlist(sessionId = sessionId, name = genreLabel(genreKey), isAutoGenerated = true)
            )
            tracksInGenre.forEach { track ->
                playlistTrackRepository.save(
                    PlaylistTrack(
                        playlistId = playlist.id!!,
                        artistName = track.artistName,
                        trackName = track.trackName,
                        url = track.url
                    )
                )
            }
            PlaylistResponse(
                id = playlist.id!!,
                name = playlist.name,
                createdAt = playlist.createdAt.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME),
                trackCount = tracksInGenre.size,
                isAutoGenerated = true
            )
        }
    }

    // FavoriteTrack.tags는 "ost,2020,rap" 처럼 개수(count) 내림차순 최대 3개가 저장돼 있음
    // (LastFmTagClient.cleanTags). 처음엔 그냥 첫 번째 태그를 장르로 썼는데, Last.fm이 매긴
    // "가장 비중 높은 태그"가 항상 장르인 건 아니라서(OST/연도/무드어가 1순위로 올 때가 있음 —
    // 예: 창모 "빌었어"가 힙합 곡인데 대표 태그는 "ost"였던 사례) 원하는 장르로 안 묶이는 문제가 있었음.
    // 그래서 태그 3개 중 우리가 아는 장르(GENRE_ALIASES)로 매핑되는 걸 우선 찾고, 하나도 없을 때만
    // 첫 번째 태그를 그대로 씀(그래도 같은 미분류 태그를 공유하는 곡끼리는 묶이게).
    private fun primaryGenreOf(track: FavoriteTrack): String? {
        val tags = track.tags?.split(",")?.map { it.trim() }?.filter { it.isNotBlank() } ?: return null
        if (tags.isEmpty()) return null

        val recognizedGenre = tags.map { it.lowercase() }.firstOrNull { GENRE_ALIASES.containsKey(it) }
        if (recognizedGenre != null) return GENRE_ALIASES.getValue(recognizedGenre)

        return normalizeGenre(tags.first())
    }

    private fun normalizeGenre(rawTag: String): String {
        val key = rawTag.trim().lowercase()
        return GENRE_ALIASES[key] ?: key
    }

    private fun genreLabel(genreKey: String): String =
        GENRE_LABELS[genreKey] ?: genreKey.replaceFirstChar { it.uppercase() }

    companion object {
        // 장르 하나짜리 재생목록은 큰 의미가 없어서, 최소 이 개수 이상 모여야 재생목록으로 만듦
        private const val MIN_TRACKS_PER_GENRE_PLAYLIST = 2

        // Last.fm 태그는 크라우드소싱이라 같은 장르도 표기가 제각각("kpop"/"k-pop", "hip hop"/"hip-hop")임 —
        // 커버리지보다 정확도를 택한 LastFmTagClient.ARTIST_SELF_TAG_ALIASES와 같은 트레이드오프로, 자주
        // 나올 만한 표기만 좁게 등록해둠(완전한 사전은 아님).
        private val GENRE_ALIASES: Map<String, String> = mapOf(
            "kpop" to "kpop", "k-pop" to "kpop", "korean pop" to "kpop",
            "hiphop" to "hiphop", "hip hop" to "hiphop", "hip-hop" to "hiphop", "rap" to "hiphop",
            "rnb" to "rnb", "r&b" to "rnb", "r & b" to "rnb",
            "ballad" to "ballad", "ballads" to "ballad",
            "rock" to "rock",
            "pop" to "pop",
            "indie" to "indie", "indie pop" to "indie", "indie rock" to "indie",
            "electronic" to "electronic", "edm" to "electronic", "dance" to "electronic",
            "acoustic" to "acoustic", "folk" to "acoustic",
            "jazz" to "jazz",
            "classical" to "classical"
        )

        private val GENRE_LABELS: Map<String, String> = mapOf(
            "kpop" to "케이팝",
            "hiphop" to "힙합",
            "rnb" to "알앤비",
            "ballad" to "발라드",
            "rock" to "록",
            "pop" to "팝",
            "indie" to "인디",
            "electronic" to "일렉트로닉",
            "acoustic" to "어쿠스틱",
            "jazz" to "재즈",
            "classical" to "클래식"
        )
    }
}
