package com.unbeat.playlist.userplaylist

import com.unbeat.playlist.userplaylist.dto.PlaylistRequest
import com.unbeat.playlist.userplaylist.dto.PlaylistResponse
import com.unbeat.playlist.userplaylist.dto.PlaylistTrackRequest
import com.unbeat.playlist.userplaylist.dto.PlaylistTrackResponse
import org.springframework.stereotype.Service
import java.time.format.DateTimeFormatter

@Service
class PlaylistService(
    private val playlistRepository: PlaylistRepository,
    private val playlistTrackRepository: PlaylistTrackRepository
) {

    fun list(sessionId: String): List<PlaylistResponse> =
        playlistRepository.findBySessionIdOrderByCreatedAtDesc(sessionId).map { it.toResponse() }

    fun create(sessionId: String, request: PlaylistRequest): PlaylistResponse {
        val name = request.name.trim().ifBlank { "새 재생목록" }
        val saved = playlistRepository.save(Playlist(sessionId = sessionId, name = name))
        return saved.toResponse()
    }

    fun delete(sessionId: String, playlistId: Long): Boolean {
        val playlist = playlistRepository.findById(playlistId).orElse(null) ?: return false
        if (playlist.sessionId != sessionId) return false
        playlistTrackRepository.deleteByPlaylistId(playlistId)
        playlistRepository.delete(playlist)
        return true
    }

    fun getTracks(sessionId: String, playlistId: Long): List<PlaylistTrackResponse>? {
        val playlist = playlistRepository.findById(playlistId).orElse(null) ?: return null
        if (playlist.sessionId != sessionId) return null
        return playlistTrackRepository.findByPlaylistIdOrderByAddedAtDesc(playlistId).map { it.toResponse() }
    }

    // 이미 그 재생목록에 있는 곡이면 새로 안 만들고 기존 걸 그대로 반환 (FavoriteTrackService.add와 같은 멱등 처리)
    fun addTrack(sessionId: String, playlistId: Long, request: PlaylistTrackRequest): PlaylistTrackResponse? {
        val playlist = playlistRepository.findById(playlistId).orElse(null) ?: return null
        if (playlist.sessionId != sessionId) return null

        val existing = playlistTrackRepository.findByPlaylistIdAndArtistNameAndTrackName(
            playlistId, request.artistName, request.trackName
        )
        if (existing != null) return existing.toResponse()

        val saved = playlistTrackRepository.save(
            PlaylistTrack(
                playlistId = playlistId,
                artistName = request.artistName,
                trackName = request.trackName,
                url = request.trackUrl,
                imageUrl = request.imageUrl
            )
        )
        return saved.toResponse()
    }

    fun removeTrack(sessionId: String, playlistId: Long, trackId: Long): Boolean {
        val playlist = playlistRepository.findById(playlistId).orElse(null) ?: return false
        if (playlist.sessionId != sessionId) return false

        val track = playlistTrackRepository.findById(trackId).orElse(null) ?: return false
        if (track.playlistId != playlistId) return false

        playlistTrackRepository.delete(track)
        return true
    }

    private fun Playlist.toResponse() = PlaylistResponse(
        id = id!!,
        name = name,
        createdAt = createdAt.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME),
        trackCount = playlistTrackRepository.countByPlaylistId(id!!).toInt(),
        isAutoGenerated = isAutoGenerated
    )

    private fun PlaylistTrack.toResponse() = PlaylistTrackResponse(
        id = id!!,
        artistName = artistName,
        trackName = trackName,
        url = url,
        imageUrl = imageUrl,
        addedAt = addedAt.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
    )
}
