package com.unbeat.playlist.userplaylist

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.LocalDateTime

/**
 * 사용자가 직접 만드는 재생목록(예: "출퇴근길에 듣는 노래"). FavoriteTrack(즐겨찾기 별표)과는 별개 개념 —
 * 별표는 "이 곡 좋다"를 빠르게 표시하는 것이고, 재생목록은 유튜브 뮤직 사이드바("주누 플레이리스트",
 * "나중" 등)처럼 사용자가 이름을 정해 직접 곡을 골라 담는 것. 태그 기반 자동 그룹핑을 시도했다가
 * "내가 원하는 건 이게 아니다, 직접 만드는 재생목록이다"라는 명확한 피드백을 받고 새로 만든 도메인.
 *
 * isAutoGenerated: "새 재생목록을 누르면 매번 이름 타이핑하고 곡 일일이 넣는 게 뻔하다, 내가 들은 곡을
 * 분석해서 장르별로 알아서 만들어졌으면 좋겠다"는 후속 피드백으로 추가. 수동 재생목록과 같은 테이블/API를
 * 쓰되, 이 플래그로 "AutoPlaylistService가 관리하는 것"과 "사용자가 직접 관리하는 것"을 구분함 —
 * 자동 생성 버튼을 다시 누르면 이 플래그가 true인 것만 지우고 최신 즐겨찾기 기준으로 다시 만듦.
 */
@Entity
@Table(name = "playlists")
class Playlist(
    @Column(name = "session_id", nullable = false, length = 64)
    val sessionId: String,

    @Column(name = "name", nullable = false, length = 100)
    var name: String,

    @Column(name = "is_auto_generated", nullable = false)
    val isAutoGenerated: Boolean = false,

    @Column(name = "created_at", nullable = false)
    val createdAt: LocalDateTime = LocalDateTime.now()
) {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null
}
