package com.unbeat.playlist.userplaylist

import org.springframework.data.jpa.repository.JpaRepository

interface PlaylistRepository : JpaRepository<Playlist, Long> {
    fun findBySessionIdOrderByCreatedAtDesc(sessionId: String): List<Playlist>
    fun findBySessionIdAndIsAutoGenerated(sessionId: String, isAutoGenerated: Boolean): List<Playlist>
}
