"use client";

import { useState } from "react";
import { createPortal } from "react-dom";
import type { Playlist, PlaylistTrack } from "@/lib/playlistApi";

type PlaylistDetailOverlayProps = {
  playlist: Playlist;
  // undefined = 아직 로딩 중 (아코디언 시절과 같은 지연 로딩 캐시를 그대로 재사용)
  tracks: PlaylistTrack[] | undefined;
  onClose: () => void;
  // 곡 이름을 직접 누르면 그 한 곡만 바로 재생 (기존 "비슷한 곡 라디오" 흐름 그대로)
  onPlayTrack: (track: { name: string; artist: string; image?: string | null }) => void;
  // 체크박스로 고른 곡들을 순서대로 이어재생(repeat=false) / 반복재생(repeat=true)
  onPlaySelected: (tracks: PlaylistTrack[], repeat: boolean) => void;
  onAddSelectedToPlaylist: (tracks: PlaylistTrack[]) => void;
  onRemoveTrack: (trackId: number) => void;
  onDeleteSelected: (trackIds: number[]) => void;
};

// 멜론 앱 재생목록 화면(체크박스 + 하단 선택반복/믹스업/다운/담기/삭제 액션바)을 참고해서 추가.
// "다운"(우린 오디오 파일이 없음)과 "믹스업"(우린 AI 믹스 서비스가 없음)은 Unbeat 특성상 그대로
// 구현할 수 없어서 빼고, 실제로 의미 있는 4개(이어재생/반복재생/담기/삭제)만 골라서 구현 — 사용자가
// 직접 고른 선택지.
// 전체화면 오버레이로 만든 이유: 사이드바 아코디언(좁은 폭)에 체크박스+하단 액션바까지 욱여넣으면
// 곡이 몇 개만 넘어가도 답답해질 게 뻔해서, MiniPlayer의 "확장 재생 화면"과 같은 패턴(전체 화면
// createPortal)을 재사용함.
export default function PlaylistDetailOverlay({
  playlist,
  tracks,
  onClose,
  onPlayTrack,
  onPlaySelected,
  onAddSelectedToPlaylist,
  onRemoveTrack,
  onDeleteSelected,
}: PlaylistDetailOverlayProps) {
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set());
  // "삭제 누르면 바로 없어지는 게 아니라 한 번 물어봤으면 좋겠다"는 피드백으로 추가 — 특히
  // "전체 선택" 상태에서 실수로 "삭제"를 누르면 재생목록 전체가 한 번에 날아갈 수 있어서, 확인
  // 단계 없이 바로 지우는 건 위험하다고 판단. 개별 ✕(한 곡)는 실수해도 되돌리기 쉬운 작은 동작이라
  // 그대로 두고, 여러 곡을 한 번에 지우는 액션바 "삭제"에만 확인 모달을 붙임.
  const [isConfirmingDelete, setIsConfirmingDelete] = useState(false);

  const list = tracks ?? [];
  const selectedTracks = list.filter((t) => selectedIds.has(t.id));
  const hasSelection = selectedTracks.length > 0;

  function toggle(id: number) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function toggleAll() {
    setSelectedIds((prev) => (prev.size === list.length ? new Set() : new Set(list.map((t) => t.id))));
  }

  if (typeof document === "undefined") return null;

  return createPortal(
    <div className="fixed inset-0 z-40 flex flex-col bg-neutral-950">
      <div className="flex items-center justify-between border-b border-white/10 px-6 py-4">
        <button
          type="button"
          onClick={onClose}
          aria-label="닫기"
          className="rounded-full p-2 text-white/50 hover:bg-white/10 hover:text-white"
        >
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="h-5 w-5"
            aria-hidden="true"
          >
            <path d="M6 9l6 6 6-6" />
          </svg>
        </button>
        <div className="min-w-0 text-center">
          <p className="truncate text-sm font-semibold">
            {playlist.isAutoGenerated && "✨ "}
            {playlist.name}
          </p>
          <p className="text-xs text-white/40">{list.length}곡</p>
        </div>
        <div className="w-9" />
      </div>

      <div className="mx-auto flex w-full max-w-2xl min-h-0 flex-1 flex-col overflow-hidden px-4 pt-3">
        {list.length > 0 && (
          <button
            type="button"
            onClick={toggleAll}
            className="mb-2 flex items-center gap-2 self-start rounded-md px-2 py-1 text-xs text-white/50 hover:bg-white/5 hover:text-white/80"
          >
            <input
              type="checkbox"
              readOnly
              checked={selectedIds.size === list.length}
              className="pointer-events-none accent-accent"
            />
            {selectedIds.size === list.length ? "전체 해제" : "전체 선택"}
          </button>
        )}

        <div className="min-h-0 flex-1 overflow-y-auto pb-4">
          {tracks === undefined ? (
            <p className="p-4 text-sm text-white/40">불러오는 중...</p>
          ) : list.length === 0 ? (
            <p className="p-4 text-sm text-white/40">아직 곡이 없어요.</p>
          ) : (
            <div className="flex flex-col gap-1">
              {list.map((t) => (
                <div
                  key={t.id}
                  className="flex items-center gap-3 rounded-md px-2 py-2 hover:bg-white/5"
                >
                  <input
                    type="checkbox"
                    checked={selectedIds.has(t.id)}
                    onChange={() => toggle(t.id)}
                    className="shrink-0 accent-accent"
                  />
                  <button
                    type="button"
                    onClick={() =>
                      onPlayTrack({ name: t.trackName, artist: t.artistName, image: t.imageUrl })
                    }
                    className="flex min-w-0 flex-1 items-center gap-3 text-left"
                  >
                    <div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded bg-white/5">
                      {t.imageUrl ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img src={t.imageUrl} alt={t.trackName} className="h-full w-full object-cover" />
                      ) : (
                        <span className="text-sm text-white/25">♪</span>
                      )}
                    </div>
                    <div className="min-w-0">
                      <p className="truncate text-sm">{t.trackName}</p>
                      <p className="truncate text-xs text-white/50">{t.artistName}</p>
                    </div>
                  </button>
                  <button
                    type="button"
                    onClick={() => onRemoveTrack(t.id)}
                    aria-label="재생목록에서 삭제"
                    className="shrink-0 rounded-full p-1.5 text-white/30 hover:bg-white/10 hover:text-white"
                  >
                    ✕
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* 하단 액션바 — 멜론 재생목록의 선택반복/믹스업/다운/담기/삭제 바를 참고. 아무것도 선택 안 하면
          다 비활성화해서, "체크 안 했는데 눌려서 이상한 게 실행됐다"는 실수를 막음. */}
      <div className="border-t border-white/10 bg-neutral-900/80 px-4 py-3 backdrop-blur">
        <div className="mx-auto flex max-w-2xl items-center justify-around">
          <button
            type="button"
            disabled={!hasSelection}
            onClick={() => onPlaySelected(selectedTracks, false)}
            className="flex flex-col items-center gap-1 rounded-md px-3 py-1.5 text-xs text-white/70 hover:bg-white/5 hover:text-white disabled:opacity-30 disabled:hover:bg-transparent"
          >
            <span className="text-base leading-none">▶</span>
            이어재생
          </button>
          <button
            type="button"
            disabled={!hasSelection}
            onClick={() => onPlaySelected(selectedTracks, true)}
            className="flex flex-col items-center gap-1 rounded-md px-3 py-1.5 text-xs text-white/70 hover:bg-white/5 hover:text-white disabled:opacity-30 disabled:hover:bg-transparent"
          >
            <span className="text-base leading-none">🔁</span>
            반복재생
          </button>
          <button
            type="button"
            disabled={!hasSelection}
            onClick={() => onAddSelectedToPlaylist(selectedTracks)}
            className="flex flex-col items-center gap-1 rounded-md px-3 py-1.5 text-xs text-white/70 hover:bg-white/5 hover:text-white disabled:opacity-30 disabled:hover:bg-transparent"
          >
            <span className="text-base leading-none">＋</span>
            담기
          </button>
          <button
            type="button"
            disabled={!hasSelection}
            onClick={() => setIsConfirmingDelete(true)}
            className="flex flex-col items-center gap-1 rounded-md px-3 py-1.5 text-xs text-red-400/80 hover:bg-white/5 hover:text-red-400 disabled:opacity-30 disabled:hover:bg-transparent"
          >
            <span className="text-base leading-none">🗑</span>
            삭제
          </button>
        </div>
      </div>

      {/* 삭제 확인 모달 — z-50이라 이 화면(z-40) 위에 뜸(AddToPlaylistModal과 같은 이유) */}
      {isConfirmingDelete && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4"
          onClick={() => setIsConfirmingDelete(false)}
        >
          <div
            className="w-full max-w-sm rounded-lg border border-white/10 bg-neutral-900 p-4"
            onClick={(e) => e.stopPropagation()}
          >
            <p className="mb-1 text-sm font-medium">
              선택한 {selectedTracks.length}곡을 삭제할까요?
            </p>
            <p className="mb-4 text-xs text-white/40">
              "{playlist.name}" 재생목록에서만 지워져요. 되돌릴 수 없어요.
            </p>
            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setIsConfirmingDelete(false)}
                className="rounded-md px-3 py-1.5 text-sm text-white/60 hover:bg-white/10"
              >
                취소
              </button>
              <button
                type="button"
                onClick={() => {
                  onDeleteSelected(selectedTracks.map((t) => t.id));
                  setSelectedIds(new Set());
                  setIsConfirmingDelete(false);
                }}
                className="rounded-md bg-red-500/90 px-3 py-1.5 text-sm text-white"
              >
                삭제
              </button>
            </div>
          </div>
        </div>
      )}
    </div>,
    document.body
  );
}
