package com.unbeat.playlist.userplaylist.dto

data class PlaylistRequest(
    val name: String
)

data class PlaylistResponse(
    val id: Long,
    val name: String,
    val createdAt: String,
    val trackCount: Int,
    val isAutoGenerated: Boolean
)

data class PlaylistTrackRequest(
    val artistName: String,
    val trackName: String,
    val trackUrl: String? = null,
    val imageUrl: String? = null
)

data class PlaylistTrackResponse(
    val id: Long,
    val artistName: String,
    val trackName: String,
    val url: String?,
    val imageUrl: String?,
    val addedAt: String
)
