package com.unbeat.playlist.userplaylist

import com.unbeat.playlist.favoritetrack.FavoriteTrack
import com.unbeat.playlist.favoritetrack.FavoriteTrackRepository
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.mockito.kotlin.any
import org.mockito.kotlin.mock
import org.mockito.kotlin.never
import org.mockito.kotlin.times
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever

class AutoPlaylistServiceTest {

    private val favoriteTrackRepository: FavoriteTrackRepository = mock()
    private val playlistRepository: PlaylistRepository = mock()
    private val playlistTrackRepository: PlaylistTrackRepository = mock()
    private val service = AutoPlaylistService(favoriteTrackRepository, playlistRepository, playlistTrackRepository)

    @Test
    fun `같은 대표 태그를 가진 곡이 2곡 이상이면 자동 재생목록을 만든다`() {
        val track1 = FavoriteTrack(sessionId = "s1", artistName = "IU", trackName = "Blueming", tags = "kpop,ballad")
        val track2 = FavoriteTrack(sessionId = "s1", artistName = "IVE", trackName = "LOVE DIVE", tags = "kpop,dance")
        whenever(favoriteTrackRepository.findBySessionIdOrderByCreatedAtDesc("s1"))
            .thenReturn(listOf(track1, track2))
        whenever(playlistRepository.findBySessionIdAndIsAutoGenerated("s1", true)).thenReturn(emptyList())
        val saved = Playlist(sessionId = "s1", name = "케이팝", isAutoGenerated = true).apply { id = 10L }
        whenever(playlistRepository.save(any())).thenReturn(saved)

        val result = service.generate("s1")

        assertEquals(1, result.size)
        assertEquals("케이팝", result[0].name)
        assertEquals(2, result[0].trackCount)
        assertTrue(result[0].isAutoGenerated)
        verify(playlistTrackRepository, times(2)).save(any())
    }

    @Test
    fun `대표 태그를 가진 곡이 1곡뿐이면 재생목록을 만들지 않는다`() {
        val track1 = FavoriteTrack(
            sessionId = "s1", artistName = "잔나비", trackName = "주저하는 연인들을 위해", tags = "rock"
        )
        whenever(favoriteTrackRepository.findBySessionIdOrderByCreatedAtDesc("s1")).thenReturn(listOf(track1))
        whenever(playlistRepository.findBySessionIdAndIsAutoGenerated("s1", true)).thenReturn(emptyList())

        val result = service.generate("s1")

        assertTrue(result.isEmpty())
        verify(playlistRepository, never()).save(any())
    }

    @Test
    fun `대표 태그가 장르가 아니어도 태그 목록 안에 아는 장르가 있으면 그걸로 분류한다`() {
        // 실제로 창모 "빌었어"가 대표 태그는 "ost"인데 3번째 태그가 "rap"이었던 사례를 재현.
        val track1 = FavoriteTrack(sessionId = "s1", artistName = "창모", trackName = "빌었어", tags = "ost,2020,rap")
        val track2 = FavoriteTrack(sessionId = "s1", artistName = "창모", trackName = "METEOR", tags = "2019,hip hop")
        whenever(favoriteTrackRepository.findBySessionIdOrderByCreatedAtDesc("s1"))
            .thenReturn(listOf(track1, track2))
        whenever(playlistRepository.findBySessionIdAndIsAutoGenerated("s1", true)).thenReturn(emptyList())
        val saved = Playlist(sessionId = "s1", name = "힙합", isAutoGenerated = true).apply { id = 20L }
        whenever(playlistRepository.save(any())).thenReturn(saved)

        val result = service.generate("s1")

        assertEquals(1, result.size)
        assertEquals("힙합", result[0].name)
        assertEquals(2, result[0].trackCount)
    }

    @Test
    fun `태그가 없는 곡은 분류에서 제외된다`() {
        val track1 = FavoriteTrack(sessionId = "s1", artistName = "A", trackName = "B", tags = null)
        val track2 = FavoriteTrack(sessionId = "s1", artistName = "C", trackName = "D", tags = "")
        whenever(favoriteTrackRepository.findBySessionIdOrderByCreatedAtDesc("s1"))
            .thenReturn(listOf(track1, track2))
        whenever(playlistRepository.findBySessionIdAndIsAutoGenerated("s1", true)).thenReturn(emptyList())

        val result = service.generate("s1")

        assertTrue(result.isEmpty())
    }

    @Test
    fun `다시 실행하면 이전 자동 생성 재생목록은 지우고 새로 만든다`() {
        val track1 = FavoriteTrack(sessionId = "s1", artistName = "A", trackName = "B", tags = "rock")
        val track2 = FavoriteTrack(sessionId = "s1", artistName = "C", trackName = "D", tags = "rock")
        whenever(favoriteTrackRepository.findBySessionIdOrderByCreatedAtDesc("s1"))
            .thenReturn(listOf(track1, track2))
        val previousAuto = Playlist(sessionId = "s1", name = "록", isAutoGenerated = true).apply { id = 5L }
        whenever(playlistRepository.findBySessionIdAndIsAutoGenerated("s1", true)).thenReturn(listOf(previousAuto))
        val saved = Playlist(sessionId = "s1", name = "록", isAutoGenerated = true).apply { id = 6L }
        whenever(playlistRepository.save(any())).thenReturn(saved)

        service.generate("s1")

        verify(playlistTrackRepository).deleteByPlaylistId(5L)
        verify(playlistRepository).deleteAll(listOf(previousAuto))
    }
}
