import { getSessionId } from "@/lib/session";

// FastAPI 백엔드(api.ts)와 별도 서비스. 포트도 다르고(8081), 언어/프레임워크도 다르다
// (Spring Boot/Kotlin). 대신 세션 식별 방식(X-Session-Id)만은 동일하게 맞춘다.
const PLAYLIST_API_BASE_URL =
  process.env.NEXT_PUBLIC_PLAYLIST_API_URL ?? "http://127.0.0.1:8081";

export type Favorite = {
  id: number;
  artistName: string;
  imageUrl: string | null;
  createdAt: string;
};

async function playlistFetch<T>(path: string, options: RequestInit = {}): Promise<T> {
  const res = await fetch(`${PLAYLIST_API_BASE_URL}${path}`, {
    ...options,
    cache: "no-store",
    headers: {
      "X-Session-Id": getSessionId(),
      // api.ts와 동일한 이유 — ngrok 경고 페이지가 fetch 응답에 끼어들어 JSON 파싱이
      // 깨지는 걸 막음 (§ngrok-skip-browser-warning).
      "ngrok-skip-browser-warning": "true",
      ...(options.body ? { "Content-Type": "application/json" } : {}),
      ...options.headers,
    },
  });
  if (!res.ok) {
    throw new Error(`즐겨찾기 API 요청 실패: ${res.status}`);
  }
  if (res.status === 204) {
    return undefined as T;
  }
  return res.json() as Promise<T>;
}

export function getFavorites(): Promise<Favorite[]> {
  return playlistFetch<Favorite[]>("/favorites");
}

export function addFavorite(artistName: string, imageUrl: string | null): Promise<Favorite> {
  return playlistFetch<Favorite>("/favorites", {
    method: "POST",
    body: JSON.stringify({ artistName, imageUrl }),
  });
}

export function removeFavorite(id: number): Promise<void> {
  return playlistFetch<void>(`/favorites/${id}`, { method: "DELETE" });
}

export type FavoriteTrack = {
  id: number;
  artistName: string;
  trackName: string;
  tags: string[];
  url: string | null;
  createdAt: string;
  lastOpenedAt: string | null;
};

export function getFavoriteTracks(): Promise<FavoriteTrack[]> {
  return playlistFetch<FavoriteTrack[]>("/favorite-tracks");
}

export function addFavoriteTrack(
  artistName: string,
  trackName: string,
  trackUrl: string | null
): Promise<FavoriteTrack> {
  return playlistFetch<FavoriteTrack>("/favorite-tracks", {
    method: "POST",
    body: JSON.stringify({ artistName, trackName, trackUrl }),
  });
}

export function removeFavoriteTrack(id: number): Promise<void> {
  return playlistFetch<void>(`/favorite-tracks/${id}`, { method: "DELETE" });
}

// 즐겨찾기한 곡 카드를 클릭해서 원곡 링크로 나갈 때 "재생 의도" 신호로 기록.
// 나중에 "몇 개월간 안 열어본 곡" 자동 분류 배치의 입력 데이터가 됨.
export function markFavoriteTrackOpened(id: number): Promise<FavoriteTrack> {
  return playlistFetch<FavoriteTrack>(`/favorite-tracks/${id}/open`, { method: "PATCH" });
}

// "즐겨찾기해놓고 오래 안 들은 곡"을 찾아줌 — "지워도 될까요?"라고 먼저 물어보는 정리 기능용.
// 기본 6개월. 무작정 지우지 않고 후보만 반환하며, 실제 삭제는 사용자가 고른 것만
// removeFavoriteTrack을 개별 호출해서 처리함.
export function getStaleFavoriteTracks(months = 6): Promise<FavoriteTrack[]> {
  return playlistFetch<FavoriteTrack[]>(`/favorite-tracks/stale?months=${months}`);
}

// 즐겨찾기(별표)와는 별개 도메인 — 별표는 "이 곡 좋다"는 빠른 표시고, 재생목록은
// 사용자가 이름을 직접 정해서 곡을 골라 담는 것(유튜브 뮤직 사이드바 "새 재생목록"과 같은 개념).
export type Playlist = {
  id: number;
  name: string;
  createdAt: string;
  trackCount: number;
  isAutoGenerated: boolean;
};

export type PlaylistTrack = {
  id: number;
  artistName: string;
  trackName: string;
  url: string | null;
  imageUrl: string | null;
  addedAt: string;
};

export function getPlaylists(): Promise<Playlist[]> {
  return playlistFetch<Playlist[]>("/playlists");
}

export function createPlaylist(name: string): Promise<Playlist> {
  return playlistFetch<Playlist>("/playlists", {
    method: "POST",
    body: JSON.stringify({ name }),
  });
}

export function deletePlaylist(id: number): Promise<void> {
  return playlistFetch<void>(`/playlists/${id}`, { method: "DELETE" });
}

export function getPlaylistTracks(playlistId: number): Promise<PlaylistTrack[]> {
  return playlistFetch<PlaylistTrack[]>(`/playlists/${playlistId}/tracks`);
}

export function addTrackToPlaylist(
  playlistId: number,
  artistName: string,
  trackName: string,
  trackUrl: string | null,
  imageUrl: string | null
): Promise<PlaylistTrack> {
  return playlistFetch<PlaylistTrack>(`/playlists/${playlistId}/tracks`, {
    method: "POST",
    body: JSON.stringify({ artistName, trackName, trackUrl, imageUrl }),
  });
}

export function removeTrackFromPlaylist(playlistId: number, trackId: number): Promise<void> {
  return playlistFetch<void>(`/playlists/${playlistId}/tracks/${trackId}`, { method: "DELETE" });
}

// "매번 이름 타이핑하고 곡 일일이 넣는 게 뻔하다, 내가 들은 곡 분석해서 장르별로 알아서 만들어졌으면
// 좋겠다"는 피드백으로 추가. 즐겨찾기한 곡의 Last.fm 태그를 서버에서 분석해서 장르별 재생목록을
// 통째로 만들어줌 — 다시 눌러도 이전 자동 생성 결과를 지우고 최신 즐겨찾기 기준으로 재생성함.
export function generateAutoPlaylists(): Promise<Playlist[]> {
  return playlistFetch<Playlist[]>("/playlists/auto-generate", { method: "POST" });
}
